GET http://localhost:3001/bets

###

POST http://localhost:3001/bets/new
Content-Type: application/json

{
    "id": 1,
    "betDescription": "Third Bet Test",
    "bettor1": "Mark",
    "bettor2": "Nick"
}

###

DELETE http://localhost:3001/bets/delete/61ef4918c7aaf0dbcb0283ee

###

